WITH DateSeries AS
(
	SELECT CAST('01-01-2022' AS DATE) AS MyDate

	UNION ALL

	SELECT DATEADD(DAY,1,MyDate) FROM DateSeries
	WHERE MyDate < Cast('12-31-2022' as DATE)
)


SELECT * FROM DateSeries OPTION(MAXRECURSION 365)